/*! Code generated by Coframe AI Editor */
(() => {
  var b = (e, n) => () => (e && (n = e((e = 0))), n);
  var h = (e, n) => () => (n || e((n = { exports: {} }).exports, n), n.exports);
  function a(e, n, ...o) {
    if (e == null) {
      let s = S(),
        i = n && Object.keys(n).length > 0,
        l = o && o.length > 0,
        f;
      i
        ? (f = `<${e}
  ${Object.entries(n).map(([r, u]) => `${r}=${JSON.stringify(u)}`).join(`
  `)}${l ? ">" : ""}`)
        : (f = `<${e}${l ? ">" : ""}`);
      let c;
      throw (
        (l
          ? (c = `
  {/* children.length: ${o.length} */}
</${e}>`)
          : (c = i
              ? `
/>`
              : "/>"),
        new Error(`Invalid element type: \`${e}\`.

**Hint**: Look for code like this:
${f}${c}
${s ? `within ${JSON.stringify(s)}.` : ""}
`))
      );
    }
    if (e === g) {
      let s = document.createDocumentFragment();
      return y(s, o), s;
    }
    if (typeof e == "function") return e({ ...(n || {}), children: T(o) });
    let t =
      typeof e == "string"
        ? document.createElement(e)
        : document.createElement(String(e));
    return n && k(t, n), y(t, o), t;
  }
  function S() {
    return new Error().stack
      ?.split(
        `
`
      )?.[3]
      ?.trim()
      .replace(/^at\s+/, "");
  }
  function k(e, n) {
    for (let o in n) {
      if (o === "key") continue;
      let t = n[o];
      if (o === "ref") {
        typeof t == "function"
          ? t(e)
          : t && typeof t == "object" && (t.current = e);
        continue;
      }
      if (o === "class" || o === "className") {
        w(e, t);
        continue;
      }
      if (o === "style") {
        C(e, t);
        continue;
      }
      if (o === "dataset" && t && typeof t == "object") {
        for (let i in t) e.dataset[i] = String(t[i]);
        continue;
      }
      if (o === "dangerouslySetInnerHTML" && t && typeof t == "object") {
        e.innerHTML = t.__html ?? "";
        continue;
      }
      if (o.startsWith("on") && typeof t == "function") {
        let i = o.slice(2).toLowerCase();
        e.addEventListener(i, t);
        continue;
      }
      let s = o === "for" ? "htmlFor" : o;
      try {
        s in e && typeof e[s] != "function"
          ? (e[s] = t)
          : t !== !1 && t != null && e.setAttribute(o, String(t));
      } catch {
        t !== !1 && t != null && e.setAttribute(o, String(t));
      }
    }
  }
  function w(e, n) {
    n &&
      (typeof n == "string"
        ? (e.className = n)
        : Array.isArray(n)
        ? (e.className = n.filter(Boolean).join(" "))
        : typeof n == "object" &&
          (e.className = Object.keys(n)
            .filter((o) => n[o])
            .join(" ")));
  }
  function C(e, n) {
    if (!n) return;
    if (typeof n == "string") {
      e.style.cssText = n;
      return;
    }
    let o = e.style;
    for (let t in n) {
      let s = n[t];
      s == null ||
        s === !1 ||
        (t in o ? (o[t] = String(s)) : e.style.setProperty(t, String(s)));
    }
  }
  function y(e, n) {
    let o = (t) => {
      t == null ||
        t === !1 ||
        (Array.isArray(t)
          ? t.forEach(o)
          : t instanceof Node
          ? e.appendChild(t)
          : e.appendChild(document.createTextNode(String(t))));
    };
    n.forEach(o);
  }
  function T(e) {
    return e.length <= 1 ? e[0] : e;
  }
  var g,
    m = b(() => {
      "use strict";
      g = Symbol.for("JSX.Fragment");
    });
  var F = h(() => {
    m();
    var p = {
        name: "CF Benefits List - Memory Air: Add Key Benefits Checklist",
      },
      E = v(p);
    if (!E) return !1;
    q(N, A);
    function A() {
      p.name,
        document.querySelector("body")?.setAttribute("cf-test-active", p.name);
      let e = window.innerWidth < 768,
        n = e
          ? document.querySelector("#lp-pom-text-118")
          : document.querySelector("#lp-pom-text-422");
      if (n) {
        if (!e) {
          let i = document.querySelector("#lp-pom-text-421");
          if (i) {
            let r = parseInt(i.style.top || getComputedStyle(i).top);
            i.style.top = r - 40 + "px";
          }
          let l = document.querySelector("#lp-pom-text-422");
          if (l) {
            let r = parseInt(l.style.top || getComputedStyle(l).top);
            l.style.top = r - 40 + "px";
          }
          let f = document.querySelector("#lp-pom-button-423");
          f && (f.style.top = "630px");
          let c = document.querySelector("#lp-pom-box-417");
          if (c) {
            let r = parseInt(c.style.top || getComputedStyle(c).top);
            c.style.top = r + 20 + "px";
          }
        }
        if (e) {
          let i = document.querySelector("#lp-pom-box-116");
          i && (i.style.height = "410px");
          let l = document.querySelector("#lp-pom-button-115");
          l && (l.style.top = "362px"),
            [
              "#lp-pom-image-120",
              "#lp-pom-block-194",
              "#lp-pom-text-195",
              "#lp-pom-text-197",
              "#lp-pom-image-137",
              "#lp-pom-block-18",
              "#lp-pom-block-32",
              "#lp-pom-block-36",
              "#lp-pom-block-150",
              "#lp-pom-block-198",
              "#lp-pom-block-200",
              "#lp-pom-block-63",
              "#lp-pom-block-67",
              "#lp-pom-block-73",
              "#lp-pom-block-81",
            ].forEach((r) => {
              let u = document.querySelector(r);
              if (u) {
                let x = parseInt(u.style.top || getComputedStyle(u).top);
                (u.style.top = x + 171 + "px"), `${r}`;
              }
            });
          let c = document.querySelector("#lp-pom-block-194");
          c && (c.style.height = "350px");
        }
        let o = "485px",
          t = "10px"; // Fix mobile positioning - make it more visible
        if (e) {
          t = "20px"; // Move more to the left for better visibility
          o = "250px"; // Adjust top position to be more visible
        }
        let s = a($, { isMobile: e, mobileTop: o, mobileLeft: t });
        n.insertAdjacentElement("afterend", s),
          (window.CFQ = window.CFQ || []),
          window.CFQ.push({ emit: "variantRendered" });
      } else
        console.error(
          `Target element not found: ${
            e ? "#lp-pom-text-118" : "#lp-pom-text-422"
          }`
        );
    }
    function N() {
      try {
        let e = typeof window.CF < "u",
          n = `body[cf-test-active="${p.name}"]`,
          t = !document.querySelector(n);
        `${n}`; // Fix: Check for either mobile or desktop element
        let s =
          !!document.querySelector("#lp-pom-text-422") ||
          !!document.querySelector("#lp-pom-text-118");
        return e && t && s;
      } catch (e) {
        return console.error("Check error:", e), !1;
      }
    }
    function $({ isMobile: e, mobileTop: n, mobileLeft: o }) {
      return a(
        "div",
        {
          className: "cf:absolute cf:block",
          style: {
            position: "absolute",
            left: e ? "60px" : "680px",
            top: e ? n || "270px" : "500px",
            width: e ? "280px" : "375px",
            height: "auto",
            zIndex: e ? 999 : 211,
            transform: e ? "scale(0.85)" : "none",
            transformOrigin: e ? "0px 0px" : "50% 50%",
            backgroundColor: "transparent",
            padding: e ? "10px 10px 10px 20px" : "0px 0px 0px 25px",
            borderRadius: e ? "8px" : "0px",
            margin: "0px",
            border: "none",
            boxSizing: "content-box",
            overflow: "visible",
            opacity: "1",
            visibility: "visible",
          },
        },
        a(
          "ul",
          { className: "cf:list-none cf:flex cf:flex-col cf:gap-2" },
          a(d, {
            text: "226% Memory Boost",
            iconUrl:
              "https://duploservices-prod-mark-1-coframe-render-images-897729117657.s3.us-west-2.amazonaws.com/cro-agent-images/memoryair/4fffa25b-c16b-44cf-85e4-33184c8fdc00.webp?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5CBGTHXMTQMHTEJ4%2F20251015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20251015T090915Z&X-Amz-Expires=86400&X-Amz-Signature=8a7416a2d6be77462e588becf205b8086c1f69416ed7891970110c58a468c258&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
            isMobile: e,
          }),
          a(d, {
            text: "Feel Years Younger",
            iconUrl:
              "https://duploservices-prod-mark-1-coframe-render-images-897729117657.s3.us-west-2.amazonaws.com/cro-agent-images/memoryair/2ce4f80c-a08c-40ea-9d4f-eed1d5a08fcc.webp?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5CBGTHXMTQMHTEJ4%2F20251015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20251015T090931Z&X-Amz-Expires=86400&X-Amz-Signature=08cb66ffa780606c55409b65044565201f81e2ab023a52a54df758847c8af6ff&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
            isMobile: e,
          }),
          a(d, {
            text: "Works While Sleeping",
            iconUrl:
              "https://duploservices-prod-mark-1-coframe-render-images-897729117657.s3.us-west-2.amazonaws.com/cro-agent-images/memoryair/8ca63b29-27df-494b-96dc-d2ca26ebc9d6.webp?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA5CBGTHXMTQMHTEJ4%2F20251015%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20251015T090945Z&X-Amz-Expires=86400&X-Amz-Signature=39c01cf67dad2341f639a10dd52a9f973e3354e5dded6b94dade155ea5b1d4e2&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject",
            isMobile: e,
          })
        )
      );
    }
    function d({ text: e, iconUrl: n, isMobile: o }) {
      return a(
        "li",
        { className: "cf:flex cf:items-start cf:gap-[10px]" },
        a("img", {
          src: n,
          alt: "benefit icon",
          className: "cf:flex-shrink-0 cf:mt-[1px]",
          style: {
            width: o ? "18px" : "20px",
            height: o ? "18px" : "20px",
            borderRadius: "50%",
            objectFit: "cover",
          },
        }),
        a(
          "span",
          {
            className: "cf:text-black cf:leading-normal",
            style: {
              fontSize: o ? "16px" : "20px",
              lineHeight: o ? "1.4" : "1.5",
            },
          },
          e
        )
      );
    }
    function q(e, n, o = !1) {
      let t = () => e() && (!o && s.disconnect(), n());
      var s = new MutationObserver(t);
      s.observe(document.documentElement, { childList: !0, subtree: !0 }),
        t(),
        o || setTimeout(() => s.disconnect(), 1e4);
    }
    function v() {
      let e = window.CF || { qaTesting: !1, testsRunning: [] };
      return e.testsRunning.find((n) => n.name == p.name)
        ? !1
        : ((e.testsRunning = [...e.testsRunning, p]),
          (window.CF = { ...window.CF, ...e }),
          { ...window.CF });
    }
  });
  F();
})();

(function injectCoframeVariantCss() {
  try {
    var style = document.createElement("style");
    style.type = "text/css";
    style.dataset.coframe = "variant-css";
    style.textContent =
      '@layer properties{@supports (((-webkit-hyphens:none)) and (not (margin-trim:inline))) or ((-moz-orient:inline) and (not (color:rgb(from red r g b)))){*,:before,:after,::backdrop{--tw-leading:initial}}}:root,:host{--cf-color-black:#000;--cf-spacing:.25rem;--cf-leading-normal:1.5}.cf\\:absolute{position:absolute}.cf\\:mt-\\[1px\\]{margin-top:1px}.cf\\:mt-\\[4px\\]{margin-top:4px}.cf\\:block{display:block}.cf\\:flex{display:flex}.cf\\:h-5{height:calc(var(--cf-spacing)*5)}.cf\\:w-5{width:calc(var(--cf-spacing)*5)}.cf\\:flex-shrink-0{flex-shrink:0}.cf\\:list-none{list-style-type:none}.cf\\:flex-col{flex-direction:column}.cf\\:items-start{align-items:flex-start}.cf\\:gap-2{gap:calc(var(--cf-spacing)*2)}.cf\\:gap-\\[10px\\]{gap:10px}.cf\\:leading-normal{--tw-leading:var(--cf-leading-normal);line-height:var(--cf-leading-normal)}.cf\\:text-black{color:var(--cf-color-black)}@property --tw-leading{syntax:"*";inherits:false}';
    document.head.appendChild(style);
  } catch (e) {
    console.error("Failed to inject variant CSS", e);
  }
})();
